# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67907c21fc67d6ff5d30bb39db5e82144599aada04624aecbdb691c5b0cdc9914d6a8d17aa6a95cda56b8497296948c629a1dc03a996441efaf25cd17365e54

test:
  secret_key_base: 8c782492542bab8d7cf2149cf069a6209d9ea9e922fbfcfd0cad299470241a88c1e3bec7f1cbff603c09061b21bd13173412c8805d927664201132ec2380376b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
